"""业务异常与错误码。"""

from fastapi import HTTPException, status


class AppException(HTTPException):
    """带 error_code 的业务异常。"""

    def __init__(self, error_code: str, message: str, http_status: int = status.HTTP_400_BAD_REQUEST):
        super().__init__(status_code=http_status, detail={"error_code": error_code, "message": message})


# 常用错误码常量，和 04 文档保持一致。
AUTH_FAILED = "AUTH_FAILED"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
PERMISSION_DENIED = "PERMISSION_DENIED"
INVALID_TICKER = "INVALID_TICKER"
STOCK_NOT_SUPPORTED = "STOCK_NOT_SUPPORTED"
NEWS_NOT_FOUND = "NEWS_NOT_FOUND"
DATA_NOT_FOUND = "DATA_NOT_FOUND"
MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
PREDICTION_NOT_FOUND = "PREDICTION_NOT_FOUND"
BACKTEST_RUN_NOT_FOUND = "BACKTEST_RUN_NOT_FOUND"
BACKTEST_NOT_READY = "BACKTEST_NOT_READY"
BACKTEST_FINAL_POSITION_NOT_FOUND = "BACKTEST_FINAL_POSITION_NOT_FOUND"
USER_NOT_FOUND = "USER_NOT_FOUND"
USERNAME_EXISTS = "USERNAME_EXISTS"
PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH"
CANNOT_DELETE_SELF = "CANNOT_DELETE_SELF"
CANNOT_DISABLE_SELF = "CANNOT_DISABLE_SELF"
CANNOT_REMOVE_LAST_ADMIN = "CANNOT_REMOVE_LAST_ADMIN"
INTERNAL_ERROR = "INTERNAL_ERROR"
